// Template for opencomputer/agents/<agent>/tools/app.ts, generated by
// scripts/prepare-agent.mjs with the app origin from OPENMUSE_APP_ORIGIN and
// the agent's name. The OpenComputer CLI reads defineConnection() origins from
// source, so the origin must be a literal in the generated file.
import { bearer, defineConnection, useSecret } from "@opencomputer/agent";

// The OpenMuse app's agent-facing routes. The installation secret is attached
// by OpenComputer to each request; agent code never sees it.
export const app = defineConnection({
  id: "openmuse-app",
  origin: "__APP_ORIGIN__",
  methods: ["GET", "POST", "PUT"],
  pathPrefix: "/api/agent/",
  headers: {
    Authorization: bearer(useSecret("OPENMUSE_AGENT_SECRET")),
    Accept: "application/json",
    "User-Agent": "openmuse-__AGENT__",
  },
});

export async function call(method: "GET" | "POST" | "PUT", path: string, body?: unknown, signal?: AbortSignal) {
  const response = await app.fetch(path, {
    method,
    signal,
    headers: body === undefined ? {} : { "Content-Type": "application/json" },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
  });
  let json: unknown = null;
  try {
    json = await response.json();
  } catch {
    json = null;
  }
  return { status: response.status, json };
}
