"use client";
import { useState, type FormEvent } from "react";

export default function LoginPage() {
  const [secret, setSecret] = useState("");
  const [error, setError] = useState<string>();
  const [busy, setBusy] = useState(false);

  async function submit(event: FormEvent) {
    event.preventDefault();
    setBusy(true);
    setError(undefined);
    try {
      const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ secret }) });
      if (response.ok) { window.location.assign("/"); return; }
      setError(response.status === 429 ? "Too many attempts; wait 15 minutes." : response.status === 401 ? "That secret is not right." : `Login failed (${response.status}).`);
    } catch {
      setError("Login failed.");
    } finally {
      setBusy(false);
      setSecret("");
    }
  }

  return (
    <main className="login">
      <h1>OpenMuse</h1>
      <form onSubmit={submit}>
        <label htmlFor="secret">Owner login secret</label>
        <input id="secret" type="password" autoComplete="current-password" value={secret} onChange={(e) => setSecret(e.target.value)} autoFocus />
        <button className="primary" type="submit" disabled={busy || !secret}>Sign in</button>
        {error ? <p className="notice" role="alert">{error}</p> : null}
        <p className="hint">The secret was generated by <code>npm run setup</code> and lives in the deployment&apos;s environment. Lost it? Run <code>npm run setup -- --rotate</code>.</p>
      </form>
    </main>
  );
}
