// Stages what the two agents need before doctor/deploy:
//  1. fixture notes -> opencomputer/agents/*/memory/fixtures.generated.ts
//     (the agent-side memory adapter's fallback until project memory lands)
//  2. scripts/templates/app-connection.ts -> each agent's tools/app.ts
//     with the app origin from OPENMUSE_APP_ORIGIN (the CLI reads
//     defineConnection() origins from source, so it must be a literal)
//  3. removes the CLI's previous generated runtime so doctor does not scan it.
import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { loadEnvFile } from "node:process";
import { parseNote } from "./notes.mjs";

const root = new URL("../", import.meta.url);
if (existsSync(new URL(".env.local", root))) loadEnvFile(new URL(".env.local", root));

const agents = ["coordinator", "topic-worker"];

const profile = parseNote(await readFile(new URL("fixtures/notes/profile.md", root), "utf8"));
const topicFiles = (await readdir(new URL("fixtures/notes/topics/", root))).filter((name) => name.endsWith(".md")).sort();
const topics = [];
for (const name of topicFiles) {
  const note = parseNote(await readFile(new URL(`fixtures/notes/topics/${name}`, root), "utf8"));
  topics.push({ id: name.replace(/\.md$/, ""), ...note });
}
const overview = topics.map((t) => `${t.id} | ${t.title} | ${t.summary} | (fixture)`).join("\n");
const generated = `// Generated by scripts/prepare-agent.mjs from fixtures/notes. Do not edit.
export const fixtureProfile = ${JSON.stringify(profile.text)};
export const fixtureTopicsOverview = ${JSON.stringify(overview)};
`;

const origin = process.env.OPENMUSE_APP_ORIGIN?.trim();
if (!origin) throw new Error("Set OPENMUSE_APP_ORIGIN (npm run setup -- --origin https://...) before preparing the agents");
const url = new URL(origin);
if (url.protocol !== "https:" || url.pathname !== "/" || url.search || url.hash) {
  throw new Error("OPENMUSE_APP_ORIGIN must be an https origin without a path");
}
const template = await readFile(new URL("scripts/templates/app-connection.ts", root), "utf8");

for (const agent of agents) {
  const dir = new URL(`opencomputer/agents/${agent}/`, root);
  await rm(new URL(".opencomputer/", dir), { recursive: true, force: true });
  await writeFile(new URL("memory/fixtures.generated.ts", dir), generated);
  await writeFile(
    new URL("tools/app.ts", dir),
    template.replace("__APP_ORIGIN__", url.origin).replace("__AGENT__", agent),
  );
}
console.log(`Prepared agents: ${topics.length} fixture topics, app origin ${url.origin}.`);
