/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as AppTopicsIdRouteImport } from './routes/_app.topics.$id'
import { Route as ApiAgentNotesRouteImport } from './routes/api/agent/notes'
import { Route as ApiAgentProfileRouteImport } from './routes/api/agent/profile'
import { Route as ApiAgentStartTopicRouteImport } from './routes/api/agent/start-topic'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiConversationIndexRouteImport } from './routes/api/conversation/index'
import { Route as ApiConversationReplaceRouteImport } from './routes/api/conversation/replace'
import { Route as ApiTopicsIndexRouteImport } from './routes/api/topics/index'
import { Route as ApiAgentTopicsIdRouteImport } from './routes/api/agent/topics/$id'
import { Route as ApiInternalReturnPathTickRouteImport } from './routes/api/internal/return-path/tick'
import { Route as ApiSessionsIdActionRouteImport } from './routes/api/sessions/$id/$action'
import { Route as ApiTopicsIdIndexRouteImport } from './routes/api/topics/$id/index'
import { Route as ApiTopicsIdArchiveRouteImport } from './routes/api/topics/$id/archive'
import { Route as ApiTopicsIdNotesRouteImport } from './routes/api/topics/$id/notes'
import { Route as ApiTopicsIdRenameRouteImport } from './routes/api/topics/$id/rename'
import { Route as ApiTopicsIdReplaceWorkerRouteImport } from './routes/api/topics/$id/replace-worker'
import { Route as ApiTopicsIdTurnsRouteImport } from './routes/api/topics/$id/turns'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopicsIdRoute = AppTopicsIdRouteImport.update({
  id: '/topics/$id',
  path: '/topics/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAgentNotesRoute = ApiAgentNotesRouteImport.update({
  id: '/api/agent/notes',
  path: '/api/agent/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentProfileRoute = ApiAgentProfileRouteImport.update({
  id: '/api/agent/profile',
  path: '/api/agent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStartTopicRoute = ApiAgentStartTopicRouteImport.update({
  id: '/api/agent/start-topic',
  path: '/api/agent/start-topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationIndexRoute = ApiConversationIndexRouteImport.update({
  id: '/api/conversation/',
  path: '/api/conversation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationReplaceRoute = ApiConversationReplaceRouteImport.update({
  id: '/api/conversation/replace',
  path: '/api/conversation/replace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsIndexRoute = ApiTopicsIndexRouteImport.update({
  id: '/api/topics/',
  path: '/api/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTopicsIdRoute = ApiAgentTopicsIdRouteImport.update({
  id: '/api/agent/topics/$id',
  path: '/api/agent/topics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalReturnPathTickRoute =
  ApiInternalReturnPathTickRouteImport.update({
    id: '/api/internal/return-path/tick',
    path: '/api/internal/return-path/tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsIdActionRoute = ApiSessionsIdActionRouteImport.update({
  id: '/api/sessions/$id/$action',
  path: '/api/sessions/$id/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsIdIndexRoute = ApiTopicsIdIndexRouteImport.update({
  id: '/api/topics/$id/',
  path: '/api/topics/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsIdArchiveRoute = ApiTopicsIdArchiveRouteImport.update({
  id: '/api/topics/$id/archive',
  path: '/api/topics/$id/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsIdNotesRoute = ApiTopicsIdNotesRouteImport.update({
  id: '/api/topics/$id/notes',
  path: '/api/topics/$id/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsIdRenameRoute = ApiTopicsIdRenameRouteImport.update({
  id: '/api/topics/$id/rename',
  path: '/api/topics/$id/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsIdReplaceWorkerRoute =
  ApiTopicsIdReplaceWorkerRouteImport.update({
    id: '/api/topics/$id/replace-worker',
    path: '/api/topics/$id/replace-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTopicsIdTurnsRoute = ApiTopicsIdTurnsRouteImport.update({
  id: '/api/topics/$id/turns',
  path: '/api/topics/$id/turns',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/api/profile': typeof ApiProfileRoute
  '/topics/$id': typeof AppTopicsIdRoute
  '/api/agent/notes': typeof ApiAgentNotesRoute
  '/api/agent/profile': typeof ApiAgentProfileRoute
  '/api/agent/start-topic': typeof ApiAgentStartTopicRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/conversation/replace': typeof ApiConversationReplaceRoute
  '/api/conversation/': typeof ApiConversationIndexRoute
  '/api/topics/': typeof ApiTopicsIndexRoute
  '/api/agent/topics/$id': typeof ApiAgentTopicsIdRoute
  '/api/internal/return-path/tick': typeof ApiInternalReturnPathTickRoute
  '/api/sessions/$id/$action': typeof ApiSessionsIdActionRoute
  '/api/topics/$id/archive': typeof ApiTopicsIdArchiveRoute
  '/api/topics/$id/notes': typeof ApiTopicsIdNotesRoute
  '/api/topics/$id/rename': typeof ApiTopicsIdRenameRoute
  '/api/topics/$id/replace-worker': typeof ApiTopicsIdReplaceWorkerRoute
  '/api/topics/$id/turns': typeof ApiTopicsIdTurnsRoute
  '/api/topics/$id/': typeof ApiTopicsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/profile': typeof ApiProfileRoute
  '/': typeof AppIndexRoute
  '/topics/$id': typeof AppTopicsIdRoute
  '/api/agent/notes': typeof ApiAgentNotesRoute
  '/api/agent/profile': typeof ApiAgentProfileRoute
  '/api/agent/start-topic': typeof ApiAgentStartTopicRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/conversation/replace': typeof ApiConversationReplaceRoute
  '/api/conversation': typeof ApiConversationIndexRoute
  '/api/topics': typeof ApiTopicsIndexRoute
  '/api/agent/topics/$id': typeof ApiAgentTopicsIdRoute
  '/api/internal/return-path/tick': typeof ApiInternalReturnPathTickRoute
  '/api/sessions/$id/$action': typeof ApiSessionsIdActionRoute
  '/api/topics/$id/archive': typeof ApiTopicsIdArchiveRoute
  '/api/topics/$id/notes': typeof ApiTopicsIdNotesRoute
  '/api/topics/$id/rename': typeof ApiTopicsIdRenameRoute
  '/api/topics/$id/replace-worker': typeof ApiTopicsIdReplaceWorkerRoute
  '/api/topics/$id/turns': typeof ApiTopicsIdTurnsRoute
  '/api/topics/$id': typeof ApiTopicsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/profile': typeof ApiProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/topics/$id': typeof AppTopicsIdRoute
  '/api/agent/notes': typeof ApiAgentNotesRoute
  '/api/agent/profile': typeof ApiAgentProfileRoute
  '/api/agent/start-topic': typeof ApiAgentStartTopicRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/conversation/replace': typeof ApiConversationReplaceRoute
  '/api/conversation/': typeof ApiConversationIndexRoute
  '/api/topics/': typeof ApiTopicsIndexRoute
  '/api/agent/topics/$id': typeof ApiAgentTopicsIdRoute
  '/api/internal/return-path/tick': typeof ApiInternalReturnPathTickRoute
  '/api/sessions/$id/$action': typeof ApiSessionsIdActionRoute
  '/api/topics/$id/archive': typeof ApiTopicsIdArchiveRoute
  '/api/topics/$id/notes': typeof ApiTopicsIdNotesRoute
  '/api/topics/$id/rename': typeof ApiTopicsIdRenameRoute
  '/api/topics/$id/replace-worker': typeof ApiTopicsIdReplaceWorkerRoute
  '/api/topics/$id/turns': typeof ApiTopicsIdTurnsRoute
  '/api/topics/$id/': typeof ApiTopicsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/profile'
    | '/topics/$id'
    | '/api/agent/notes'
    | '/api/agent/profile'
    | '/api/agent/start-topic'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/conversation/replace'
    | '/api/conversation/'
    | '/api/topics/'
    | '/api/agent/topics/$id'
    | '/api/internal/return-path/tick'
    | '/api/sessions/$id/$action'
    | '/api/topics/$id/archive'
    | '/api/topics/$id/notes'
    | '/api/topics/$id/rename'
    | '/api/topics/$id/replace-worker'
    | '/api/topics/$id/turns'
    | '/api/topics/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/profile'
    | '/'
    | '/topics/$id'
    | '/api/agent/notes'
    | '/api/agent/profile'
    | '/api/agent/start-topic'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/conversation/replace'
    | '/api/conversation'
    | '/api/topics'
    | '/api/agent/topics/$id'
    | '/api/internal/return-path/tick'
    | '/api/sessions/$id/$action'
    | '/api/topics/$id/archive'
    | '/api/topics/$id/notes'
    | '/api/topics/$id/rename'
    | '/api/topics/$id/replace-worker'
    | '/api/topics/$id/turns'
    | '/api/topics/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/api/profile'
    | '/_app/'
    | '/_app/topics/$id'
    | '/api/agent/notes'
    | '/api/agent/profile'
    | '/api/agent/start-topic'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/conversation/replace'
    | '/api/conversation/'
    | '/api/topics/'
    | '/api/agent/topics/$id'
    | '/api/internal/return-path/tick'
    | '/api/sessions/$id/$action'
    | '/api/topics/$id/archive'
    | '/api/topics/$id/notes'
    | '/api/topics/$id/rename'
    | '/api/topics/$id/replace-worker'
    | '/api/topics/$id/turns'
    | '/api/topics/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiAgentNotesRoute: typeof ApiAgentNotesRoute
  ApiAgentProfileRoute: typeof ApiAgentProfileRoute
  ApiAgentStartTopicRoute: typeof ApiAgentStartTopicRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiConversationReplaceRoute: typeof ApiConversationReplaceRoute
  ApiConversationIndexRoute: typeof ApiConversationIndexRoute
  ApiTopicsIndexRoute: typeof ApiTopicsIndexRoute
  ApiAgentTopicsIdRoute: typeof ApiAgentTopicsIdRoute
  ApiInternalReturnPathTickRoute: typeof ApiInternalReturnPathTickRoute
  ApiSessionsIdActionRoute: typeof ApiSessionsIdActionRoute
  ApiTopicsIdArchiveRoute: typeof ApiTopicsIdArchiveRoute
  ApiTopicsIdNotesRoute: typeof ApiTopicsIdNotesRoute
  ApiTopicsIdRenameRoute: typeof ApiTopicsIdRenameRoute
  ApiTopicsIdReplaceWorkerRoute: typeof ApiTopicsIdReplaceWorkerRoute
  ApiTopicsIdTurnsRoute: typeof ApiTopicsIdTurnsRoute
  ApiTopicsIdIndexRoute: typeof ApiTopicsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/topics/$id': {
      id: '/_app/topics/$id'
      path: '/topics/$id'
      fullPath: '/topics/$id'
      preLoaderRoute: typeof AppTopicsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agent/notes': {
      id: '/api/agent/notes'
      path: '/api/agent/notes'
      fullPath: '/api/agent/notes'
      preLoaderRoute: typeof ApiAgentNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/profile': {
      id: '/api/agent/profile'
      path: '/api/agent/profile'
      fullPath: '/api/agent/profile'
      preLoaderRoute: typeof ApiAgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/start-topic': {
      id: '/api/agent/start-topic'
      path: '/api/agent/start-topic'
      fullPath: '/api/agent/start-topic'
      preLoaderRoute: typeof ApiAgentStartTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/': {
      id: '/api/conversation/'
      path: '/api/conversation'
      fullPath: '/api/conversation/'
      preLoaderRoute: typeof ApiConversationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/replace': {
      id: '/api/conversation/replace'
      path: '/api/conversation/replace'
      fullPath: '/api/conversation/replace'
      preLoaderRoute: typeof ApiConversationReplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/': {
      id: '/api/topics/'
      path: '/api/topics'
      fullPath: '/api/topics/'
      preLoaderRoute: typeof ApiTopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/topics/$id': {
      id: '/api/agent/topics/$id'
      path: '/api/agent/topics/$id'
      fullPath: '/api/agent/topics/$id'
      preLoaderRoute: typeof ApiAgentTopicsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/return-path/tick': {
      id: '/api/internal/return-path/tick'
      path: '/api/internal/return-path/tick'
      fullPath: '/api/internal/return-path/tick'
      preLoaderRoute: typeof ApiInternalReturnPathTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id/$action': {
      id: '/api/sessions/$id/$action'
      path: '/api/sessions/$id/$action'
      fullPath: '/api/sessions/$id/$action'
      preLoaderRoute: typeof ApiSessionsIdActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/$id/': {
      id: '/api/topics/$id/'
      path: '/api/topics/$id'
      fullPath: '/api/topics/$id/'
      preLoaderRoute: typeof ApiTopicsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/$id/archive': {
      id: '/api/topics/$id/archive'
      path: '/api/topics/$id/archive'
      fullPath: '/api/topics/$id/archive'
      preLoaderRoute: typeof ApiTopicsIdArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/$id/notes': {
      id: '/api/topics/$id/notes'
      path: '/api/topics/$id/notes'
      fullPath: '/api/topics/$id/notes'
      preLoaderRoute: typeof ApiTopicsIdNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/$id/rename': {
      id: '/api/topics/$id/rename'
      path: '/api/topics/$id/rename'
      fullPath: '/api/topics/$id/rename'
      preLoaderRoute: typeof ApiTopicsIdRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/$id/replace-worker': {
      id: '/api/topics/$id/replace-worker'
      path: '/api/topics/$id/replace-worker'
      fullPath: '/api/topics/$id/replace-worker'
      preLoaderRoute: typeof ApiTopicsIdReplaceWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/$id/turns': {
      id: '/api/topics/$id/turns'
      path: '/api/topics/$id/turns'
      fullPath: '/api/topics/$id/turns'
      preLoaderRoute: typeof ApiTopicsIdTurnsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTopicsIdRoute: typeof AppTopicsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTopicsIdRoute: AppTopicsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiAgentNotesRoute: ApiAgentNotesRoute,
  ApiAgentProfileRoute: ApiAgentProfileRoute,
  ApiAgentStartTopicRoute: ApiAgentStartTopicRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiConversationReplaceRoute: ApiConversationReplaceRoute,
  ApiConversationIndexRoute: ApiConversationIndexRoute,
  ApiTopicsIndexRoute: ApiTopicsIndexRoute,
  ApiAgentTopicsIdRoute: ApiAgentTopicsIdRoute,
  ApiInternalReturnPathTickRoute: ApiInternalReturnPathTickRoute,
  ApiSessionsIdActionRoute: ApiSessionsIdActionRoute,
  ApiTopicsIdArchiveRoute: ApiTopicsIdArchiveRoute,
  ApiTopicsIdNotesRoute: ApiTopicsIdNotesRoute,
  ApiTopicsIdRenameRoute: ApiTopicsIdRenameRoute,
  ApiTopicsIdReplaceWorkerRoute: ApiTopicsIdReplaceWorkerRoute,
  ApiTopicsIdTurnsRoute: ApiTopicsIdTurnsRoute,
  ApiTopicsIdIndexRoute: ApiTopicsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
